### ISSUE TITLE
When will release full training code?

### ISSUE THREAD

**Issue by 08173021** [SysCV/ovtrack#11]
Hello, when the full training code will be released, as you said six months ago?

**Comment by siyliepfl** [comment]
We've released the full training code for the tracker:  To train your tracker with generated images, please follow the instruction [here](https://github.com/SysCV/ovtrack/blob/799c4e499f6fe0bb7a21295e892aed7a1ea49a3d/docs/GET_STARTED.md?plain=1#L101)
If you want to generate the training images by yourself, please follow the guide [here](docs/OVTRACK_GEN.md).

**Comment by 08173021** [comment]
Excellent work, thank you very much!
