### ISSUE TITLE
training for the CLIP distillation part

### ISSUE THREAD

**Issue by Nathan-Li123** [SysCV/ovtrack#17]
If I want to replicate the training step of CLIP distillation, how should I proceed? Can it be achieved through the code in this repository? For example, setting the freeze_detector parameter to False. I feel like this might not be sufficient.
I am very curious about how you obtained weight files such as _ovtrack_clip_distillation.pth_. Did you use DetPro's training code to obtain the weights for _text_head_ and _image_head_?
Thanks in advance.

**Comment by siyuanliii** [comment]
yes, exactly, we use DetPro's release code for the distillation part.
