### ISSUE TITLE
question about evaluation

### ISSUE THREAD

**Issue by Nathan-Li123** [SysCV/ovtrack#20]
Your work is very inspiring. I have a question: During the evaluation, do we need to input all the novel classes from the validation set into the model for inference, or should we input the novel classes for each sequence in the validation set separately? Looking forward to your response.

**Comment by siyuanliii** [comment]
We should input all the novel classes! Otherwise, if we tell the model novel classes per sequence, it is a much easier task, since we already told the model which novel classes to expect in this certain video.
