### ISSUE TITLE
lvis_classes_v1.txt is missing

### ISSUE THREAD

**Issue by balabooooo** [SysCV/ovtrack#4]
Thanks for your work!
It seems that there's no instruction to generate lvis_classes_v1.txt. Could you please tell me how to generate this, or just share this file.
Thank you in advance.

**Comment by siyliepfl** [comment]
Thanks for your question! I added the download link in the docs/GET_STARTED.md.
I will also put it here: [ lvis_classes_v1.txt](https://drive.google.com/file/d/1CzyggqLe4aeqmDEEN-aPgIFIqZcR-Dwj/view?usp=drive_link)

**Comment by balabooooo** [comment]
Thank you!
